### ISSUE TITLE
1.0 version of paper select doesn't fire onChange handler

### ISSUE THREAD

**Issue by gkappen** [miguelcobain/ember-paper#589] opened 2016-12-14 12:25 UTC
We're converting to ember paper 1.0 but may have found an issue with paper-select. It does not reliably call the onChange handler. Especially when selecting the currently selected value. It can be reproduced on the [demo page](http://miguelcobain.github.io/ember-paper/release-1/#/components/select) (as show in the attached gif)

![select-onchange-notfired](https://cloud.githubusercontent.com/assets/4178316/21181848/26b318f4-c200-11e6-8e45-ee42fddebafa.gif)

This may be a duplicate of #404 but that doesn't give any info on the version used.

**Comment by miguelcobain** [comment] 2016-12-14 12:55
Seems related to focus. If you re-select the same option *while the select is focused*, then it doesn't seem to work. A blur must happen between.
/cc @ibarrick

**Comment by brianhjelle** [comment] 2017-04-29 02:10
If you don't move the mouse then the select doesn't work.  However, if you move the mouse just a little bit after the option menu opens it seems to work.  This problem does not occur on touch screens.

**Comment by ibarrick** [comment] 2017-04-29 16:13
@miguelcobain From what I can tell the issue is because in the `choose` function in e-p-s bails out if `(Math.abs(this.openingEvent.clientY - e.clientY) < 2)`. If you move the mouse to right right or left it won't select but if the mouse moves in the Y direction by at least 2 pixels the event will trigger. We could override that but idk what we would be giving up.

**Comment by brianhjelle** [comment] 2017-08-17 18:20
Any update on this?

**Comment by Subtletree** [comment] 2020-02-17 03:41
Looks like this will be fixed officially in EPS version 4
https://github.com/cibernox/ember-power-select/blob/fc62e26f2b681d18de77111ca0a2854213f46622/addon/components/power-select.ts#L376-L382
(No mouse move checking afaict)

**Closed** 2020-02-18 02:18 UTC
Labels: bug

**Comment by miguelcobain** [comment] 2020-02-18 02:38
1.0.0-beta.28 should have this fixed with yet another crazy hack. :(
