### ISSUE TITLE
paper-icon cannot be shown in ie 11

### ISSUE THREAD

**Issue by tmclouisluk** [miguelcobain/ember-paper#474] opened 2016-08-26 04:11 UTC
![ss](https://cloud.githubusercontent.com/assets/18186155/17993846/2797590e-6b86-11e6-9ee5-937bb5bde4b8.png)

**Comment by joukevandermaas** [comment] 2016-12-07 10:59
I cannot reproduce this. Maybe it got fixed in the meantime?

![image](https://cloud.githubusercontent.com/assets/1257578/20965111/9c5b16e2-bc74-11e6-8753-fb7492ff2ca7.png)

**Comment by miguelcobain** [comment] 2016-12-07 15:34
@joukevandermaas Very likely. Please reopen if issue persists.

**Closed by miguelcobain** 2016-12-07 15:34 UTC
