### ISSUE TITLE
Paper tabs calculate wrong position for the inkBar on app loading

### ISSUE THREAD

**Issue by gmarquet** [miguelcobain/ember-paper#858] opened 2017-11-03 16:45 UTC
go to http://miguelcobain.github.io/ember-paper/#/components/tabs (without cache enabled)
and click on the first active tab then the component should update the inkBar to the correct values.

The currentWidth of the _selectedTab seems to be wrong.
I suspect the change in width between before and after the loading of the font.

**Comment by kkgomez2** [comment] 2018-04-04 20:38
I also have this problem.

**Comment by panthony** [comment] 2019-01-12 08:11
Duplicate of #858 ?

**Closed** 2019-03-01 16:57 UTC
