### ISSUE TITLE
Cannot click secondary actions in a list item with a primary action in firefox

### ISSUE THREAD

**Issue by joukevandermaas** [miguelcobain/ember-paper#592] opened 2016-12-22 08:55 UTC
Given the following snippet (simplified, from the docs page):

```hbs
{{#paper-item onClick=(action "primaryAction") as |controls|}}
  List item with action and controls

  {{#controls.button secondary=true iconButton=true onClick=(action "secondaryAction")}}
    {{paper-icon "phone"}}
  {{/controls.button}}
{{/paper-item}}
```

In Firefox, it is not possible to trigger the secondary action. When clicking the button, it triggers the primary action instead. As far as I've been able to tell, this happens whenever you attach an event handler to something clickable within a button. In Firefox, the button gets the click, but not the nested element.

Note that in the Angular Material demo (1.0.6), it does work in Firefox. There, the secondary action is nested within the list item, but not the button:

```html
<md-list-item class="md-with-secondary md-clickable">
  <button class="md-no-style md-button md-ink-ripple">
    <div class="md-list-item-inner">
      <p>Janet Perkins</p>
    </div>
    <div class="md-ripple-container"></div>
  </button>
  <button class="md-secondary-container md-icon-button md-button md-ink-ripple">
    <md-icon>messenger</md-icon>
    <div class="md-ripple-container"> </div>
  </button>
</md-list-item>
```

### potential solutions

I do not believe it's possible to emit AM's markup with the template markup as it is. A potential solution is to make the list content into a separate contextual component also:

```hbs
{{#paper-item onClick=(action "primaryAction") as |item|}}

  {{#item.content}}
    List item with action and controls
  {{/item.content}}

  {{#item.button secondary=true iconButton=true onClick=(action "secondaryAction")}}
    {{paper-icon "phone"}}
  {{/item.button}}

{{/paper-item}}
```

could emit:

```html
<md-list-item class="md-with-secondary md-clickable">
  <button class="md-no-style md-button md-ink-ripple">
    <div class="md-list-item-inner">
      List item with actions and controls
    </div>
    <div class="md-ripple-container"></div>
  </button>
  <button class="md-secondary-container md-icon-button md-button md-ink-ripple">
    <md-icon>phone</md-icon>
    <div class="md-ripple-container"> </div>
  </button>
</md-list-item>
```

Alternatively, the `tagName` of the outer button could change into something else instead (say `div`), which requires no changes to user's templates but also fixes the issue in Firefox:

```html
<md-list-item class="md-clickable">
  <div tabindex="0" type="button" class="md-no-style md-default-theme md-button md-ink-ripple">
    <div class="md-list-item-inner">
      List item with actions and controls
    </div>
    <button tabindex="0" type="button" class="md-default-theme md-secondary md-button md-icon-button md-ink-ripple">
      <md-icon>star_border</md-icon>
      <div class="md-ripple-container"></div>
    </button>
    <div class="md-ripple-container"></div>
  </div>
</md-list-item>
```

I'll be happy to PR either of those or any other solution you can think of.

**Comment by miguelcobain** [comment] 2016-12-23 18:28
@joukevandermaas another possibility would be to preventDefault the secondary button, right?

**Comment by joukevandermaas** [comment] 2016-12-30 13:06
@miguelcobain Sorry for the delay, I was on holiday 😄 

`stopPropagation` does not work. I modified paper-button's click handler to the following:

```js
click(event) {
  event.stopPropagation();

  this.sendAction('onClick', event);
  // Prevent bubbling, if specified. If undefined, the event will bubble.
  return this.get('bubbles');
}
```

But the effect described above still occurs in Firefox.

**Comment by joukevandermaas** [comment] 2017-01-19 13:23
@miguelcobain do you have a preference on how to fix this? I think we should probably prefer to do what AM does, but that is a breaking change so it should happen before Ember Paper 1.0 is released.

**Comment by miguelcobain** [comment] 2017-01-19 13:32
@joukevandermaas this an unfortunate situation. Looks like we can't reproduce exactly what angular is doing. Looks like when there is a primary and a secondary action, they place two buttons side by side, not nested.

If this isn't possible for us, while keeping the same API, I'd rather try alternative solutions.
Changing the `button` to `div` works? The same styles are applied? We probably need  some tabindex changes to make it focusable like a button would be.

**Comment by joukevandermaas** [comment] 2017-01-19 14:26
@miguelcobain We went with this solution temporarily in our app, we changed the template to use a `<div>` instead of a `<button>`:

```hbs
{{#with (hash
  checkbox=(component "paper-checkbox" parentComponent=this bubbles=false shouldRegister=true)
  button=(component "paper-button" parentComponent=this bubbles=false shouldRegister=true skipProxy=true)
  switch=(component "paper-switch" parentComponent=this bubbles=false shouldRegister=true)
) as |controls|}}

  {{#if hasPrimaryAction}}
    {{#paper-button class="md-no-style" tagName="div" onClick=(action onClick)}}
      <div class="md-list-item-inner">
        {{yield controls}}
      </div>
    {{/paper-button}}
  {{else}}
    <div class="md-no-style md-list-item-inner">
      {{yield controls}}
    </div>
  {{/if}}

{{/with}}
```

Then we needed to add this bit of styling to make it look the same:

```scss
md-list-item .md-button.md-no-style {
  margin: 0;
  font-weight: normal;
}
```

**Comment by arschmitz** [comment] 2017-05-17 01:32
Any progress on this issue its a pretty serious deal breaker for firefox?

**Comment by miguelcobain** [comment] 2017-05-17 01:39
Ah, this should be fixed on master. Keep in mind that the API for secondary itens changed slightly, but that's just for styling purposes. Check the changelog for those changes.

Can anyone test this?

**Comment by arschmitz** [comment] 2017-05-17 01:46
Thank you! I didnt check master ( should have ) and the issue was still open

**Comment by miguelcobain** [comment] 2017-05-17 01:50
I didn't release master yet because there's a bug there that I still couldn't find the cause for. The background color for md-content is grayish there. 
Master branch updates all AM styles to latest. Somo change there caused it. Need more time to find the problem.

**Comment by Subtletree** [comment] 2017-05-17 01:54
Can't find source code for it but maybe it's not a bug?
https://github.com/angular/material/issues/10300
https://github.com/angular/material/issues/7512

**Comment by miguelcobain** [comment] 2017-05-17 01:57
@subtletree AM docs md-content is white. That's why I thought it was a bug. On a second thought they could be overriding it just for the demo app and grayish color is the default thing.

**Comment by Subtletree** [comment] 2017-05-17 01:58
Right, still seems strange to select gray as the default background color

**Comment by jacob-financeit** [comment] 2017-07-31 15:10
Just dealing with the same bug in our app. Heads up that switching a `button` to a `div` has serious potential conflicts for accessibility. (Many screenreaders and other assistive devices key strongly on the `button` tag for all kinds of behaviour)

**Comment by miguelcobain** [comment] 2017-07-31 15:18
@jacob-financeit you shouldn't be getting this problem with the latest ember-paper and the new API. Example:

```hbs
    {{#paper-item class="md-3-line" onClick=(action "goToPerson" item) as |controls|}}
      <img src={{item.img}} alt={{item.name}} class="md-avatar">
      <div class="md-list-item-text">
        <h3>{{item.name}}</h3>
        <h4>{{item.email}}</h4>
        <p>Some notes here.</p>
      </div>
      {{#controls.button secondary=true iconButton=true onClick=(action "secondaryPersonClick" item)}}
        {{paper-icon "phone"}}
      {{/controls.button}}
    {{/paper-item}}
```

let me know if this is still an issue.

**Closed by miguelcobain** 2017-07-31 15:18 UTC
Labels: bug
