### ISSUE TITLE
paper-select-dropdown persists when dialog is closed

### ISSUE THREAD

**Issue by BobrImperator** [miguelcobain/ember-paper#967] opened 2018-07-31 13:16 UTC
##   STEPS
  - Open the dialog
  - click on the category field to open drop down
  - hit ESCAPE
  - the dropdown HTML should persist
  - the components are destroyed (judging based on what ember-inspector shows)

## The heroku app
https://morning-headland-34714.herokuapp.com/

## Repo
https://github.com/BobrImperator/dropdown-not-closing-on-escape

**Comment by miguelcobain** [comment] 2018-07-31 15:34
@BobrImperator Thanks a lot for the detailed reproduction. This will make it a lot easier to solve the problem.

**Comment by schekin** [comment] 2019-01-17 21:21
How to fix this error?

**Comment by panthony** [comment] 2019-03-01 12:33
@miguelcobain @BobrImperator I think this is a duplicate of #808

**Comment by ctwoolsey** [comment] 2020-06-09 20:41
Additionally, I've created a dialog within a parent and if I click outside of the dropdown, the dropdown does not automatically close.

**Closed** 2022-01-24 22:05 UTC
Labels: bug
