### ISSUE TITLE
Paper select sometimes doesn't register clicks on the current item

### ISSUE THREAD

**Issue by jiripospisil** [miguelcobain/ember-paper#975] opened 2018-09-06 12:00 UTC
It looks like the `paper-select` component sometimes doesn't register clicks on the current item. The video shows the issue as present on the [showcase page](https://miguelcobain.github.io/ember-paper/#/components/select):

https://www.dropbox.com/s/fn5x7fz4wvkpu12/ember-paper-select.mp4?dl=0

Reproducible in Chrome 69.0.3497.81, Firefox 62.0, and Safari 11.1.2.

**Comment by gkappen** [comment] 2019-01-11 13:14
This is a duplicate of https://github.com/miguelcobain/ember-paper/issues/589

**Closed** 2020-02-18 01:27 UTC
