### ISSUE TITLE
Select not working properly

### ISSUE THREAD

**Issue by chrisitananese** [miguelcobain/ember-paper#189] opened 2015-10-06 13:38 UTC
Not quite sure if I'm missing something or if it's a bug.

Suppose I have a model with an expirationDate property set to "+1 year", for a php backend.
When adding a model a user gets to choose how long the model will be valid, so in my controller I have something like:
```javascript
availableDates: [{
    id: '+1 year',
    name: "1 year"
  }, {
    id: '+2 year',
    name: "2 years"
  }, {
    id: 'last day of december',
    name: "end of the year"
  }, ],
```
and my select looks like this:

```javascript
{{#paper-select placeholder="Some placeholder" model=model.expirationDate}}
    {{#each availableDates as |date|}}
        {{#paper-option value=date.id}}
            {{date.name}}
        {{/paper-option}}
    {{/each}}
{{/paper-select}}
```
Now in the option menu I have all the date.names but when selecting an option its showing the id. Am I missing something or is this indeed a bug @peec ?

# Menu:

![select2](https://cloud.githubusercontent.com/assets/6060101/10310022/14a7156e-6c40-11e5-9e28-1ee0b4930183.png)

# When selected

![select1](https://cloud.githubusercontent.com/assets/6060101/10310014/0e37c89a-6c40-11e5-8e67-0e972e2fd74f.png)

**Comment by jamesdixon** [comment] 2015-10-08 01:03
This is the behavior I see as well.

**Comment by TheKidCoder** [comment] 2015-10-13 19:40
Did some digging and found the answer...

This is actually by design, and I think it's a great solution.
The `{{#paper-select}}` component expects a callback method to be passed in that will be called to lookup the correct label.

So if you have this in your template:
```
{{#paper-select placeholder="Select Week" model=selectedWeek itemLabelCallback=itemLabelCallback}}
```

And this in your controller:
```coffeescript
  itemLabelCallback: (->
    ( (id) -> 
      @get('weeks').findBy('id', id).get('title')
    ).bind(@)
  ).property()
```

The `value` of the option will be passed in to the callback and you can lookup whatever data you need. I think this issue can be closed.

**Comment by jamesdixon** [comment] 2015-10-13 19:59
Thanks for digging into this @TheKidCoder.

I suppose I'm still a bit confused why this would be desirable behavior as it certainly deviates from the way one expects a typical select component to function. Care to elaborate?

**Comment by TheKidCoder** [comment] 2015-10-13 20:04
I think just given how this is component is built, it would probably have been unnecessarily difficult to hoist whatever was inside of the `{{#paper-option}}` block into the `{{paper-select-value}}` block.

This component is nice because you can put whatever markup you want into a `{{#paper-option}}` but then also keep with the same format as other inputs or form components for when the menu is closed. I know from experience that it can be hell dealing with complicated selects so this is a nice pattern IMO.

**Comment by jamesdixon** [comment] 2015-10-13 20:14
Interesting. Admittedly, I haven't looked at the code in detail, but I would have assumed that if you're already able to display the block content of `paper-option` in the menu and then show its value after selection, it would be trivial to display the block content instead.

If it's a component design issue, the solution you mentioned would certainly make sense, otherwise, it just seems like an unnecessary step that deviates from the expected behavior. 

Regardless, @peec did a great job with the implementation :+1:

**Comment by chanep** [comment] 2015-12-17 20:35
implement a controller callback just to get a label is quite annoying.
pager-option value should not become Label after select (or pager-option should have an additional property)

**Comment by DanChadwick** [comment] 2016-04-20 03:10
Yes, a item label callback is required by design. Let's close this unless there is discussion for a specific API change for `paper-select`. Please reopen as needed!

**Closed by DanChadwick** 2016-04-20 03:10 UTC
