### ISSUE TITLE
1.0.0-beta.25 no longer clears input from text-field/area

### ISSUE THREAD

**Issue by larryh** [miguelcobain/ember-paper#1092] opened 2019-07-17 13:06 UTC
Hi,

First things first: thanks for the great addon! I know it must be tough working on this (and maybe other addons) in addition to your "day job", so it is greatly appreciated.

I have a couple of textfield and textarea controls where I clear the input after a form submission in preparation for another input/submission. This has worked fine for years with ember-paper.

However, the most recent update seems to have broken this capability. Shortly after upgrading to beta.25 I ran my tests and the ones that ensured " " was in the form field after hitting "Submit" failed.

Sure enough, the text remained in the fields. I have attached screenshots of the textarea, as it is easier to see what is going on.

The first picture shows the initial state of the textarea; the second, after entering text; the third, after clicking "Submit".
 
You can barely see the " Text * " label underneath the text that I entered after clicking "Submit". But the text should be cleared, and the " Text * " label clearly visible so the user can enter another comment.

Regarding the textfield: The "Submit" button cleared out the text, but pressing the "Enter" key did not.

Backing off to 1.0.0-beat.24 fixed the problems for both the textfield and textarea.

![textarea_initial](https://user-images.githubusercontent.com/89646/61377656-4427c400-a869-11e9-8f98-452944c2ab56.png)

![textarea_with_input](https://user-images.githubusercontent.com/89646/61377665-4853e180-a869-11e9-8df3-ea5b5bfa62ea.png)

![textarea_submit](https://user-images.githubusercontent.com/89646/61377679-4db12c00-a869-11e9-8a36-e63dc3458417.png)

**Comment by backspace** [comment] 2019-07-21 15:14
I’m finding this too, in two different varieties.

The first is somewhat like @larryh’s situation: when a user changes between radio buttons, the related fields are supposed to clear. [Here](https://travis-ci.org/backspace/prison-rideshare-ui/builds/561518352#L689-L708)’s the failing test.

A GIF of it when it works:

![report-clear-working](https://user-images.githubusercontent.com/43280/61592821-bff17b80-ab9d-11e9-8d00-7c31f3438230.gif)

And what happens with `1.0.0-beta.25`:

![report-clear-broken](https://user-images.githubusercontent.com/43280/61592825-cc75d400-ab9d-11e9-8739-e22677b4534b.gif)

Another is where I’ve added a clear button to a search field. [Here](https://travis-ci.org/backspace/prison-rideshare-ui/builds/561518352#L719-L738)’s the failing test.

The action sets the search string to `undefined`. This works on the controller, as the search results update, but the field doesn’t clear:

![paper-input-clear-failure](https://user-images.githubusercontent.com/43280/61593021-e1ebfd80-ab9f-11e9-8683-662ffd9f59e6.gif)

Since there aren’t that many changes in [the changelog for this version](https://github.com/miguelcobain/ember-paper/blob/master/CHANGELOG.md#100-beta25), I’m hoping I can narrow down what broke this today and submit a PR with a test to prevent regressions 🤞🏻

**Comment by backspace** [comment] 2019-07-21 15:30
hmm well it’s [this change](https://github.com/miguelcobain/ember-paper/pull/1076/files) but what to do about reverting it and not having #1043 become an issue again 🤔 there’s no test for it

**Comment by backspace** [comment] 2019-07-21 16:08
#1095 has a test that shows this problem, but I don’t know how to fix it without #1043 returning. I only have a single `paper-autocomplete` in my application and I’m unable to reproduce #1043 even when #1076 has been reverted, so I feel stuck.

**Comment by miguelcobain** [comment] 2019-07-25 18:16
Closed on https://github.com/miguelcobain/ember-paper/commit/f117ca0d4c6395a8fc941552b2a8a9492e157505

Fix will be released on beta.26

**Closed by miguelcobain** 2019-07-25 18:16 UTC

**Comment by larryh** [comment] 2019-07-25 19:13
Thank you for all of your work! Will definitely check it out on beta.26.

**Comment by larryh** [comment] 2019-07-30 18:35
Hi,

Just wanted to let you know that the fix you put into beta.26 solved the problem. Thanks a lot!
