### ISSUE TITLE
Ember-paper chip Click to add

### ISSUE THREAD

**Issue by bloodknight2010** [miguelcobain/ember-paper#587] opened 2016-12-09 08:16 UTC
Hello All,

 Chips with Autocomplete box does not work in chrome Version 50.0.2661.102 (64-bit)
Sometimes can't click to add custom data.

Thanks
![photo](https://cloud.githubusercontent.com/assets/5322033/21042160/282ee1a8-be1e-11e6-9a2a-6ad1f5c1f810.JPG)

**Comment by v3ss0n** [comment] 2016-12-12 13:00
Can be reproduced , that is working fine 1-2 weeks ago

**Comment by xomaczar** [comment] 2016-12-14 06:10
Can't reproduce in the latest e-p release

**Comment by v3ss0n** [comment] 2016-12-14 08:09
Can still be reproduced on : http://miguelcobain.github.io/ember-paper/release-1/#/components/chips

Do you mean working on master?

**Comment by xomaczar** [comment] 2016-12-14 14:40
Ohhh I thought not found rendered above

**Comment by v3ss0n** [comment] 2016-12-17 05:05
is this related to #589 ?

**Comment by xomaczar** [comment] 2016-12-17 06:31
No not really.

**Comment by Subtletree** [comment] 2017-01-31 23:01
@pauln's fix tested and working for me : )

**Comment by v3ss0n** [comment] 2017-02-01 12:56
thanks , so it fixed on @pauln 's fix ?

**Comment by saivarunr** [comment] 2017-04-26 06:11
Unable to add custom chip on "Not found, click to add" hook on chrome 58.0.3029.81 (64-bit), works fine on mozilla. 
Any idea why?

**Comment by pauln** [comment] 2017-04-26 06:36
@saivarunr, the fix mentioned here still hasn't been merged - pull request #632 is still open.  Once that gets merged, this should hopefully be fixed.

@miguelcobain, any idea when you might be able to look at merging this (and other chips-related PRs)?

**Comment by saivarunr** [comment] 2017-04-26 06:38
@pauln thanks for swift reply, cool! Hope that will be fixed soon. cheers.

**Closed** 2017-07-26 01:22 UTC
Labels: bug
