### ISSUE TITLE
Latest master branch does not build

### ISSUE THREAD

**Issue by cah-danmonroe** [miguelcobain/ember-paper#349] opened 2016-04-28 02:50 UTC
Installing the latest master branch fails to build.

`npm --version`  

> 2.147

`ember --version`

> ember-cli: 2.4.3
node: 4.2.3
os: darwin x64

Here are the steps I took to reproduce:

- npm cache clean
- bower cache clean
- ember new eptest
- cd eptest
- ember install https://github.com/miguelcobain/ember-paper.git#master

> Installed packages for tooling via npm.
installing ember-paper
  create app/styles/app.scss
  install bower packages hammer.js, matchMedia
  not-cached https://github.com/hammerjs/hammer.js.git#*
  not-cached https://github.com/paulirish/matchMedia.js.git#0.2.0
  resolved https://github.com/paulirish/matchMedia.js.git#0.2.0
  resolved https://github.com/hammerjs/hammer.js.git#2.0.8
Installed browser packages via Bower.
  install package ember-cli-sass
⠙ Installing packages for tooling via npmBinary downloaded and installed at /Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/darwin-x64-46/binding.node
⠸ Installing packages for tooling via npm"/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass/vendor/darwin-x64-46/binding.node" exists.
 testing binary.
Binary is fine; exiting.
Installed packages for tooling via npm.
Installed addon package.

- ember build

> Build failed.
The Broccoli Plugin: [Funnel: AngularScssFunnel] failed with:
Error: ENOENT: no such file or directory, lstat '/Users/daniel.monroe/projects/training/ember/eptest/node_modules/angular-material-source/src'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at symlink (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/symlink-or-copy/index.js:60:26)
    at symlinkOrCopySync (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/symlink-or-copy/index.js:55:5)
    at /Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/read_compat.js:58:9
    at lib$rsvp$$internal$$tryCatch (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:419:9)
The broccoli plugin was instantiated at:
    at Funnel.Plugin (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/node_modules/broccoli-funnel/index.js:44:10)
    at Class.module.exports.treeForStyles (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-paper/index.js:112:28)
    at Class._treeFor (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/models/addon.js:322:31)
    at Class.treeFor (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/models/addon.js:290:19)
    at /Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/broccoli/ember-app.js:463:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/broccoli/ember-app.js:461:30)
    at EmberApp.styles (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/broccoli/ember-app.js:1243:25)
    at EmberApp.toArray (/Users/daniel.monroe/projects/training/ember/eptest/node_modules/ember-cli/lib/broccoli/ember-app.js:1565:10)

package.json:

> {
  "name": "eptest",
  "version": "0.0.0",
  "description": "Small description for eptest goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.4.3",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.3.1",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.4.2",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-paper": "git+https://github.com/miguelcobain/ember-paper.git#1ec9596ece800afe76ad490f4f53f260b9b779e6",
    "ember-resolver": "^2.0.3",
    "loader.js": "^4.0.1"
  }
}

bower.json:

> {
  "name": "eptest",
  "dependencies": {
    "ember": "~2.4.3",
    "ember-cli-shims": "0.1.1",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "hammer.js": "^2.0.8",
    "matchMedia": "0.2.0"
  }
}

**Comment by miguelcobain** [comment] 2016-04-28 06:17
Probably related with https://github.com/miguelcobain/ember-paper/pull/343

/cc @eriktrom

**Comment by miguelcobain** [comment] 2016-04-28 06:18
We may need to check the npm version we're running in? It's sad to need to do that in 2016.

**Comment by eriktrom** [comment] 2016-04-29 08:54
It's this line: 

`/Users/daniel.monroe/projects/training/ember/eptest/node_modules/angular-material-source/src`

This builds correctly in my project with npm 3.x but that should not matter. The only difference I can see at a glance is that I added ember-paper to dependencies instead of devDependencies, but that really shouldn't matter. 

Also it's builds on travis, which uses npm 2.x so this does seem odd.

I'll take a closer look though

**Comment by eriktrom** [comment] 2016-04-29 08:56
A good smoke test, and way to work backwards is to run `npm i` inside of ember-paper itself and then npm link to your project. If that works, let me know. If not, then there is another issue going on

**Comment by cah-danmonroe** [comment] 2016-04-29 18:12
Same error after npm linking as well.

**Comment by eriktrom** [comment] 2016-04-29 20:26
@cah-danmonroe - we can pair if you'd like - try the following first though inside your project directory:

```
npm i -g npm && \
rm -rf ./node_modules && \
npm i && \ 
bower cache clean && \
bower install && \
./node_modules/.bin/ember serve
```

The problem seems to be that there is no folder `/Users/daniel.monroe/projects/training/ember/eptest/node_modules/angular-material-source/src` which is why you get this error:

> Error: ENOENT: no such file or directory, lstat '/Users/daniel.monroe/projects/training/ember/eptest/node_modules/angular-material-source/src'

Make sure to use npm 3.x with node 4.x. Let me know if your still stuck. Don't mind jumping on screenhero for a sec

**Comment by cah-danmonroe** [comment] 2016-04-30 14:57
If I switch to npm 3.8.6 with node 5.11.0, ember paper does build.  It puts angular-material-source into my project's node_modules directory.  npm version 2.x does not.

**Comment by eriktrom** [comment] 2016-04-30 16:19
Glad you got it working. Sorry about the trouble.

Node 0.12 and npm 2.x on my machine do work, and so does travis which makes this all a bit interesting. We'll see if it arises again. 

Thanks for reporting the issue @cah-danmonroe

**Comment by miguelcobain** [comment] 2016-05-03 16:03
@eriktrom From what I understand, the problem was not building ember-paper but **installing** ember-paper.

**Comment by cah-danmonroe** [comment] 2016-05-03 16:59
I think the issue still exists.  It never worked for me when I was on npm 2.147/node 4.23.  I had to upgrade for it to work.  If your intention is to support npm 2.x, then I think there is more to investigate.

**Comment by thijsvdanker** [comment] 2016-05-03 18:35
I had the same issue when running node 4.4.3 and npm 2.15.1.
The problem is with building (ember serve) as it can't find the `angular-material-source`. I agree with @miguelcobain that it's probably related to https://github.com/miguelcobain/ember-paper/pull/343

Upgrading to npm 3.x resolves the issue, but as ember-cli [recommends](http://ember-cli.com/#node) npm 2.x it would be nice if this could be fixed.

**Comment by eriktrom** [comment] 2016-05-04 17:28
thanks for letting me know, im looking further into it (now im pretty curious)

**Comment by eriktrom** [comment] 2016-05-04 20:49
Did a little digging, understand the problem better, made my best attempt in https://github.com/miguelcobain/ember-paper/pull/364

Need ya'll to try it, works on my machine, but it always has, LOL

**Comment by DanChadwick** [comment] 2016-05-04 21:11
Closing in favor of discussion in PR #346.

**Closed by DanChadwick** 2016-05-04 21:11 UTC
