### ISSUE TITLE
paper-menu: first item highlighted by default.

### ISSUE THREAD

**Issue by mhretab** [miguelcobain/ember-paper#239] opened 2015-12-08 15:27 UTC
On [paper-menu](http://miguelcobain.github.io/ember-paper/#/menu), first item is highlighted by default even if you highlight on another item. The default angular material behaviour is not like this. Is it possible to have something similar?

**Comment by DanChadwick** [comment] 2015-12-15 18:47
I noticed this too. This is because the first item is given focus. The other highlighting is because of focus. The current style make these two forms of highlighting look identical.

I'm wondering how hard it would be to blur the first menu item when another item is hovered over....

**Comment by DanChadwick** [comment] 2015-12-18 17:40
I'm not convinced this is the best solution, but I have a subclassed `paper-menu-item` to provide a leading checkmark and command key shortcuts as one might want in a drop down. In that, I added:
```javascript
  mouseEnter() {
    this._super(...arguments);
    // Remove focus from any sibling menu items by focusing on this menu-item's button.
    this.$('.md-button').focus();
  }
```
I'm not totally convinced this is the right behavior, but then I'm not sure what to make of the situation where the user is hovering over a non-focused menu item.

**Comment by DanChadwick** [comment] 2015-12-20 15:13
This focus presents a functional issue for my use case. If the users is editing a property, an input element is created in the template. Trying to use a command form the menu sets the focus on the menu, which causes the input element to lose focus, which remove the input element. It seems maybe the best solution would be to have an option to not auto-focus the menu.

**Comment by DanChadwick** [comment] 2016-04-20 02:39
This is by design, but I support the idea of an enhancement to make this optional.

**Comment by miguelcobain** [comment] 2017-08-01 14:27
I think this was fixed in latest menu versions: http://miguelcobain.github.io/ember-paper/#/components/menu

Please reopen if not.

**Closed by miguelcobain** 2017-08-01 14:27 UTC
Labels: enhancement
