### ISSUE TITLE
Defining custom style not working in new version (Alpha20)

### ISSUE THREAD

**Issue by BennyAlex** [miguelcobain/ember-paper#742] opened 2017-06-30 14:39 UTC
I definded a custom style, which worked in the old version (alpha19)
```
//app.scss

@import "color-palette";

$md-colors: (
  accent: (
    '50': #ffefe6,
    '100': #feae80,
    '200': #fe9e67,
    '300': #fe8e4d,
    '400': #fe701b,
    '500': #fe5e01,
    '600': #e45401,
    '700': #cb4b01,
    '800': #b24201,
    '900': #983801,
    'A100': #ffcfb3,
    'A200': rgba(255, 150, 0, 0.83), //checkbox color
    'A400': #feae80,
    'A700': #fe9e67,
    'contrast': $dark-contrast-color
  )
);

$accent: map_get($md-colors, accent);
```
With Alpha20, I get the error:

> WARNING: Unknown `` in $colors. `("50": #ffefe6, "100": #feae80, "200": #fe9e67, "300": #fe8e4d, "400": #fe701b, "500": #fe5e01, "600": #e45401, "700": #cb4b01, "800": #b24201, "900": #983801, "A100": #ffcfb3, "A200": rgba(255, 150, 0, 0.83), "A400": #feae80, "A700": #fe9e67, "contrast": rgba(0, 0, 0, 0.87))`
> Backtrace:
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/color-palette.scss:475, in function `color`
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/angular-material/components/button/button-theme.scss:16
> 
> WARNING: Unknown `` in $colors. `("50": #ffefe6, "100": #feae80, "200": #fe9e67, "300": #fe8e4d, "400": #fe701b, "500": #fe5e01, "600": #e45401, "700": #cb4b01, "800": #b24201, "900": #983801, "A100": #ffcfb3, "A200": rgba(255, 150, 0, 0.83), "A400": #feae80, "A700": #fe9e67, "contrast": rgba(0, 0, 0, 0.87))`
> Backtrace:
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/color-palette.scss:475, in function `color`
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/angular-material/components/button/button-theme.scss:56
> 
> WARNING: Unknown `` in $colors. `("50": #ffefe6, "100": #feae80, "200": #fe9e67, "300": #fe8e4d, "400": #fe701b, "500": #fe5e01, "600": #e45401, "700": #cb4b01, "800": #b24201, "900": #983801, "A100": #ffcfb3, "A200": rgba(255, 150, 0, 0.83), "A400": #feae80, "A700": #fe9e67, "contrast": rgba(0, 0, 0, 0.87))`
> Backtrace:
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/color-palette.scss:475, in function `color`
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/angular-material/components/button/button-theme.scss:114
> 
> WARNING: Unknown `` in $colors. `("50": #ffefe6, "100": #feae80, "200": #fe9e67, "300": #fe8e4d, "400": #fe701b, "500": #fe5e01, "600": #e45401, "700": #cb4b01, "800": #b24201, "900": #983801, "A100": #ffcfb3, "A200": rgba(255, 150, 0, 0.83), "A400": #feae80, "A700": #fe9e67, "contrast": rgba(0, 0, 0, 0.87))`
> Backtrace:
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/color-palette.scss:475, in function `color`
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/angular-material/components/button/button-theme.scss:118
> 
> WARNING: Unknown `` in $colors. `("50": #ffefe6, "100": #feae80, "200": #fe9e67, "300": #fe8e4d, "400": #fe701b, "500": #fe5e01, "600": #e45401, "700": #cb4b01, "800": #b24201, "900": #983801, "A100": #ffcfb3, "A200": rgba(255, 150, 0, 0.83), "A400": #feae80, "A700": #fe9e67, "contrast": rgba(0, 0, 0, 0.87))`
> Backtrace:
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/color-palette.scss:475, in function `color`
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/angular-material/components/button/button-theme.scss:133
> 
> WARNING: Unknown `` in $colors. `("50": #ffefe6, "100": #feae80, "200": #fe9e67, "300": #fe8e4d, "400": #fe701b, "500": #fe5e01, "600": #e45401, "700": #cb4b01, "800": #b24201, "900": #983801, "A100": #ffcfb3, "A200": rgba(255, 150, 0, 0.83), "A400": #feae80, "A700": #fe9e67, "contrast": rgba(0, 0, 0, 0.87))`
> Backtrace:
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/color-palette.scss:475, in function `color`
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/angular-material/components/button/button-theme.scss:171
> 
> WARNING: Unknown `` in $colors. `("50": #ffefe6, "100": #feae80, "200": #fe9e67, "300": #fe8e4d, "400": #fe701b, "500": #fe5e01, "600": #e45401, "700": #cb4b01, "800": #b24201, "900": #983801, "A100": #ffcfb3, "A200": rgba(255, 150, 0, 0.83), "A400": #feae80, "A700": #fe9e67, "contrast": rgba(0, 0, 0, 0.87))`
> Backtrace:
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/color-palette.scss:475, in function `color`
>         tmp/sass_compiler-input_base_path-yUyT79x4.tmp/app/styles/angular-material/components/checkbox/checkbox-theme.scss:11
> 
> The Broccoli Plugin: [BroccoliMergeTrees] failed with:
> Error: argument `$color` of `rgba($color, $alpha)` must be a color

**Comment by miguelcobain** [comment] 2017-06-30 15:59
This should be a duplicate of https://github.com/miguelcobain/ember-paper/issues/737

**Closed by miguelcobain** 2017-06-30 15:59 UTC
