### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource

### ISSUE THREAD

**Issue by robinboening** [miguelcobain/ember-paper#224] opened 2015-11-14 12:26 UTC
I get this error on heroku (not locally)

```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://rubyissues.herokuapp.com/assets/rubyissues-dc683ef8d41f45e5fdafceda1a26598f.css' with computed SHA-256 integrity 'vGH6uxiZBXnDr46nPJPx2/V82if1Sij2FDhPgXSk6xI='. The resource has been blocked.
```

It seems to be similar to this: https://github.com/ember-cli/ember-cli/issues/5040, but I can not fix it by adding an empty `integrity` attribute to the `link` tag. (I can see another integrity attribute is added automatically)

I am posting here because I broke the issue down to one of the `@import` statements in my `app.scss`:
The `@import 'ember-paper';` - When I remove this line its working.

Seems to be an issue in chrome only. No problem when using Firefox.

**Comment by mike1o1** [comment] 2015-11-14 22:54
I had a similar issue running in production, and just ended up adding the empty integrity tag to every script and link tag. It resolved it for me. Don't think there's much we can do on our end here.

Here is what my index works, and this is working fine for me. Did you add it to all tags?

*Note I haven't tested with the latest ember-cli, but this is working for me*

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Client</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {{content-for 'head'}}

    <link rel="stylesheet" href="assets/vendor.css" integrity="">
    <link rel="stylesheet" href="assets/client.css" integrity="">

    {{content-for 'head-footer'}}
  </head>
  <body layout="row">
    {{content-for 'body'}}

    <script src="assets/vendor.js" integrity=""></script>
    <script src="assets/client.js" integrity=""></script>

    {{content-for 'body-footer'}}
  </body>
</html>
```

**Comment by mansona** [comment] 2016-01-14 10:14
This issue is probably caused by some encoding problem somewhere in the included files, take a look here to follow the progress of the bug https://github.com/jonathanKingston/ember-cli-sri/issues/5 . 

The simplest way to "solve" this while we're waiting for it to get fixed is to just remove the `"ember-cli-sri": "^1.0.1",` line from your package.json and it will no longer add the integrity attribute :+1:

**Comment by jonathanKingston** [comment] 2016-01-27 20:08
@mansona you will have trouble in old Chrome's if you don't have `>1.1` anyway as that was actually Chromes issue. Removing security really isn't a good solution here please can I ask you not to advocate that. The bug you linked to talks about the issue there.

However all these issues are gone and actually `ember-cli-sri` is back in the stance of never disabling itself any more as Chrome has a stable implementation of SRI. Can I ask all three of you to `ember install ember-cli-sri@2.0.0`? Also removing any `integrity=""`'s from files unless they are generated on the fly (like testem.js)

That way you all get better security and this issue can be closed if it's ok. :smile:

**Comment by mival** [comment] 2016-02-11 17:44
I have also this issue. I am using ember-cli 2.3.0-beta.2, ember-paper 0.2.11, ember-cli-sri 2.0.0. Testing in Chrome 48.0.2564.109 Windows/Linux and Firefox 44.0.1 Linux and integrity check fails. After disabling ember-paper integrity check is working fine. Currently for me only working solution is disabling ember-cli-sri.

**Comment by jonathanKingston** [comment] 2016-02-11 22:41
@mival do you have any other addons installed that might output the shape of your code before publishing?

**Comment by mival** [comment] 2016-02-12 10:28
@jonathanKingston I use new ember-cli generated app and only install  ember-paper. Config files attached.

[bower.json.txt](https://github.com/miguelcobain/ember-paper/files/127815/bower.json.txt)
[package.json.txt](https://github.com/miguelcobain/ember-paper/files/127816/package.json.txt)

**Comment by DanChadwick** [comment] 2016-02-25 12:17
@jonathanKingston - I have the identical issue, using `ember-cli-sri@2.0.0`. I removed node_modules, bower_components, dist, and temp; npm and bower cache clean; npm and bower install. The hashes on the .js files are fine, but those on the style sheets are not, in both FireFox 44.0.2 and Chrome 48. Windows 10. I'm wondering if it is related to the sass or less build process. I'm also using ember-table, which uses less. I'm happy to provide any additional data or try any experiments to help diagnose this.

**Comment by jonathanKingston** [comment] 2016-02-26 12:21
@DanChadwick yeah less and/or sass could be running after sri calculation which certainly would give you a bad time. There has been an update to fix unicode issues but I can't see that solving anything for you. A smaller example would help right now as my time is a little limited. Thanks!

**Comment by ehntoo** [comment] 2016-03-17 14:43
I also hit this issue today. I don't have any dependencies on LESS, so this may be an issue with SASS alone?

For my app, disabling SRI entirely was an acceptable solution, so that's the route I've taken for now. I'd be willing to help test out fixes if anyone else needs a test subject, though.

**Comment by JeffreyRuder** [comment] 2016-03-18 02:38
I've also run into this issue recently. I likewise disabled SRI since the app is not being used in a production environment.

**Comment by MiguelMadero** [comment] 2016-04-06 13:40
I got the same today, with the latest of everything and sri#^2.1.0. That's an OS project see https://github.com/MiguelMadero/ember-cli-bundle-loader-consumer, so it could help as a good test case. 

Since this is just a demo, I simply blanked the integrity attribute

**Comment by chbonser** [comment] 2016-04-14 20:02
I ran into this same issue today (css files fail for SRI check in any browser when using ember cli 2.4 and ember paper).  Here is what I discovered...

ember-paper runs autoprefixer in a `postprocessTree` hook.  ember-cli-sri runs its magic in the same hook.   Because ember-cli-sri was before ember-paper in my package.json, sri runs _before_ autoprefixer.  Oops.

As a short term fix, rather than blank the integrity attribute you can move ember-paper before ember-cli-sri in your package json.

I'll submit a PR shortly to ensure that ember-paper installs after ember-cli-sri so that the package.json order doesn't matter.

**Comment by DanChadwick** [comment] 2016-04-14 20:20
@chbonser: Awesome! Can you submit the PR against branch `wip/v1.0.1`, where development is focused?

**Comment by chbonser** [comment] 2016-04-14 20:33
@DanChadwick did you mean `wip/v1.0.0`?

**Comment by DanChadwick** [comment] 2016-04-14 20:34
@miguelcobain: Just planning ahead. :stuck_out_tongue_winking_eye:

**Comment by chbonser** [comment] 2016-04-14 20:48
See PR #337. The build failed but it doesn't look like something that I caused. Please let me know if you need anything else from me.

**Comment by miguelcobain** [comment] 2016-04-15 16:36
Closed by https://github.com/miguelcobain/ember-paper/pull/337

**Closed by miguelcobain** 2016-04-15 16:36 UTC

**Comment by Juraci** [comment] 2016-11-04 20:56
I'm still having this issue, ember 2.8.0 ember-paper 1.0.0-alpha.5 ember-cli-sri 2.1.0.  When I try to open the page on chrome mobile I get exactly the same error.  Any suggestions?
